/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type DateOnly, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerCustomersEndPointsCustomersCreateCreateCustomersRequest}
 */
// @ts-ignore
export function createServerCustomersEndPointsCustomersCreateCreateCustomersRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerCustomersEndPointsCustomersCreateCreateCustomersRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerCustomersEndPointsCustomersCreateCreateCustomersResponse}
 */
// @ts-ignore
export function createServerCustomersEndPointsCustomersCreateCreateCustomersResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerCustomersEndPointsCustomersCreateCreateCustomersResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerProductsEndPointsCreateProductCreateProductRequest}
 */
// @ts-ignore
export function createServerProductsEndPointsCreateProductCreateProductRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerProductsEndPointsCreateProductCreateProductRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerProductsEndPointsCreateProductCreateProductResponse}
 */
// @ts-ignore
export function createServerProductsEndPointsCreateProductCreateProductResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerProductsEndPointsCreateProductCreateProductResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerProductsEndPointsGetProductsGetProductsResponse}
 */
// @ts-ignore
export function createServerProductsEndPointsGetProductsGetProductsResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerProductsEndPointsGetProductsGetProductsResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerProductsEndPointsGetProductsProductItem}
 */
// @ts-ignore
export function createServerProductsEndPointsGetProductsProductItemFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerProductsEndPointsGetProductsProductItem;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWeatherForecast}
 */
// @ts-ignore
export function createServerWeatherForecastFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWeatherForecast;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerCustomersEndPointsCustomersCreateCreateCustomersRequest(serverCustomersEndPointsCustomersCreateCreateCustomersRequest: Partial<ServerCustomersEndPointsCustomersCreateCreateCustomersRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { serverCustomersEndPointsCustomersCreateCreateCustomersRequest.description = n.getStringValue(); },
        "name": n => { serverCustomersEndPointsCustomersCreateCreateCustomersRequest.name = n.getStringValue(); },
        "price": n => { serverCustomersEndPointsCustomersCreateCreateCustomersRequest.price = n.getNumberValue(); },
        "stockQuantity": n => { serverCustomersEndPointsCustomersCreateCreateCustomersRequest.stockQuantity = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerCustomersEndPointsCustomersCreateCreateCustomersResponse(serverCustomersEndPointsCustomersCreateCreateCustomersResponse: Partial<ServerCustomersEndPointsCustomersCreateCreateCustomersResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { serverCustomersEndPointsCustomersCreateCreateCustomersResponse.createdAt = n.getDateValue(); },
        "description": n => { serverCustomersEndPointsCustomersCreateCreateCustomersResponse.description = n.getStringValue(); },
        "id": n => { serverCustomersEndPointsCustomersCreateCreateCustomersResponse.id = n.getStringValue(); },
        "name": n => { serverCustomersEndPointsCustomersCreateCreateCustomersResponse.name = n.getStringValue(); },
        "price": n => { serverCustomersEndPointsCustomersCreateCreateCustomersResponse.price = n.getNumberValue(); },
        "stockQuantity": n => { serverCustomersEndPointsCustomersCreateCreateCustomersResponse.stockQuantity = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerProductsEndPointsCreateProductCreateProductRequest(serverProductsEndPointsCreateProductCreateProductRequest: Partial<ServerProductsEndPointsCreateProductCreateProductRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { serverProductsEndPointsCreateProductCreateProductRequest.description = n.getStringValue(); },
        "name": n => { serverProductsEndPointsCreateProductCreateProductRequest.name = n.getStringValue(); },
        "price": n => { serverProductsEndPointsCreateProductCreateProductRequest.price = n.getNumberValue(); },
        "stockQuantity": n => { serverProductsEndPointsCreateProductCreateProductRequest.stockQuantity = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerProductsEndPointsCreateProductCreateProductResponse(serverProductsEndPointsCreateProductCreateProductResponse: Partial<ServerProductsEndPointsCreateProductCreateProductResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { serverProductsEndPointsCreateProductCreateProductResponse.createdAt = n.getDateValue(); },
        "description": n => { serverProductsEndPointsCreateProductCreateProductResponse.description = n.getStringValue(); },
        "id": n => { serverProductsEndPointsCreateProductCreateProductResponse.id = n.getStringValue(); },
        "name": n => { serverProductsEndPointsCreateProductCreateProductResponse.name = n.getStringValue(); },
        "price": n => { serverProductsEndPointsCreateProductCreateProductResponse.price = n.getNumberValue(); },
        "stockQuantity": n => { serverProductsEndPointsCreateProductCreateProductResponse.stockQuantity = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerProductsEndPointsGetProductsGetProductsResponse(serverProductsEndPointsGetProductsGetProductsResponse: Partial<ServerProductsEndPointsGetProductsGetProductsResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "products": n => { serverProductsEndPointsGetProductsGetProductsResponse.products = n.getCollectionOfObjectValues<ServerProductsEndPointsGetProductsProductItem>(createServerProductsEndPointsGetProductsProductItemFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerProductsEndPointsGetProductsProductItem(serverProductsEndPointsGetProductsProductItem: Partial<ServerProductsEndPointsGetProductsProductItem> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { serverProductsEndPointsGetProductsProductItem.createdAt = n.getDateValue(); },
        "description": n => { serverProductsEndPointsGetProductsProductItem.description = n.getStringValue(); },
        "id": n => { serverProductsEndPointsGetProductsProductItem.id = n.getStringValue(); },
        "isActive": n => { serverProductsEndPointsGetProductsProductItem.isActive = n.getBooleanValue(); },
        "name": n => { serverProductsEndPointsGetProductsProductItem.name = n.getStringValue(); },
        "price": n => { serverProductsEndPointsGetProductsProductItem.price = n.getNumberValue(); },
        "stockQuantity": n => { serverProductsEndPointsGetProductsProductItem.stockQuantity = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWeatherForecast(serverWeatherForecast: Partial<ServerWeatherForecast> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "date": n => { serverWeatherForecast.date = n.getDateOnlyValue(); },
        "summary": n => { serverWeatherForecast.summary = n.getStringValue(); },
        "temperatureC": n => { serverWeatherForecast.temperatureC = n.getNumberValue(); },
        "temperatureF": n => { serverWeatherForecast.temperatureF = n.getNumberValue(); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerCustomersEndPointsCustomersCreateCreateCustomersRequest(writer: SerializationWriter, serverCustomersEndPointsCustomersCreateCreateCustomersRequest: Partial<ServerCustomersEndPointsCustomersCreateCreateCustomersRequest> | undefined | null = {}) : void {
    if (serverCustomersEndPointsCustomersCreateCreateCustomersRequest) {
        writer.writeStringValue("description", serverCustomersEndPointsCustomersCreateCreateCustomersRequest.description);
        writer.writeStringValue("name", serverCustomersEndPointsCustomersCreateCreateCustomersRequest.name);
        writer.writeNumberValue("price", serverCustomersEndPointsCustomersCreateCreateCustomersRequest.price);
        writer.writeNumberValue("stockQuantity", serverCustomersEndPointsCustomersCreateCreateCustomersRequest.stockQuantity);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerCustomersEndPointsCustomersCreateCreateCustomersResponse(writer: SerializationWriter, serverCustomersEndPointsCustomersCreateCreateCustomersResponse: Partial<ServerCustomersEndPointsCustomersCreateCreateCustomersResponse> | undefined | null = {}) : void {
    if (serverCustomersEndPointsCustomersCreateCreateCustomersResponse) {
        writer.writeDateValue("createdAt", serverCustomersEndPointsCustomersCreateCreateCustomersResponse.createdAt);
        writer.writeStringValue("description", serverCustomersEndPointsCustomersCreateCreateCustomersResponse.description);
        writer.writeStringValue("id", serverCustomersEndPointsCustomersCreateCreateCustomersResponse.id);
        writer.writeStringValue("name", serverCustomersEndPointsCustomersCreateCreateCustomersResponse.name);
        writer.writeNumberValue("price", serverCustomersEndPointsCustomersCreateCreateCustomersResponse.price);
        writer.writeNumberValue("stockQuantity", serverCustomersEndPointsCustomersCreateCreateCustomersResponse.stockQuantity);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerProductsEndPointsCreateProductCreateProductRequest(writer: SerializationWriter, serverProductsEndPointsCreateProductCreateProductRequest: Partial<ServerProductsEndPointsCreateProductCreateProductRequest> | undefined | null = {}) : void {
    if (serverProductsEndPointsCreateProductCreateProductRequest) {
        writer.writeStringValue("description", serverProductsEndPointsCreateProductCreateProductRequest.description);
        writer.writeStringValue("name", serverProductsEndPointsCreateProductCreateProductRequest.name);
        writer.writeNumberValue("price", serverProductsEndPointsCreateProductCreateProductRequest.price);
        writer.writeNumberValue("stockQuantity", serverProductsEndPointsCreateProductCreateProductRequest.stockQuantity);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerProductsEndPointsCreateProductCreateProductResponse(writer: SerializationWriter, serverProductsEndPointsCreateProductCreateProductResponse: Partial<ServerProductsEndPointsCreateProductCreateProductResponse> | undefined | null = {}) : void {
    if (serverProductsEndPointsCreateProductCreateProductResponse) {
        writer.writeDateValue("createdAt", serverProductsEndPointsCreateProductCreateProductResponse.createdAt);
        writer.writeStringValue("description", serverProductsEndPointsCreateProductCreateProductResponse.description);
        writer.writeStringValue("id", serverProductsEndPointsCreateProductCreateProductResponse.id);
        writer.writeStringValue("name", serverProductsEndPointsCreateProductCreateProductResponse.name);
        writer.writeNumberValue("price", serverProductsEndPointsCreateProductCreateProductResponse.price);
        writer.writeNumberValue("stockQuantity", serverProductsEndPointsCreateProductCreateProductResponse.stockQuantity);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerProductsEndPointsGetProductsGetProductsResponse(writer: SerializationWriter, serverProductsEndPointsGetProductsGetProductsResponse: Partial<ServerProductsEndPointsGetProductsGetProductsResponse> | undefined | null = {}) : void {
    if (serverProductsEndPointsGetProductsGetProductsResponse) {
        writer.writeCollectionOfObjectValues<ServerProductsEndPointsGetProductsProductItem>("products", serverProductsEndPointsGetProductsGetProductsResponse.products, serializeServerProductsEndPointsGetProductsProductItem);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerProductsEndPointsGetProductsProductItem(writer: SerializationWriter, serverProductsEndPointsGetProductsProductItem: Partial<ServerProductsEndPointsGetProductsProductItem> | undefined | null = {}) : void {
    if (serverProductsEndPointsGetProductsProductItem) {
        writer.writeDateValue("createdAt", serverProductsEndPointsGetProductsProductItem.createdAt);
        writer.writeStringValue("description", serverProductsEndPointsGetProductsProductItem.description);
        writer.writeStringValue("id", serverProductsEndPointsGetProductsProductItem.id);
        writer.writeBooleanValue("isActive", serverProductsEndPointsGetProductsProductItem.isActive);
        writer.writeStringValue("name", serverProductsEndPointsGetProductsProductItem.name);
        writer.writeNumberValue("price", serverProductsEndPointsGetProductsProductItem.price);
        writer.writeNumberValue("stockQuantity", serverProductsEndPointsGetProductsProductItem.stockQuantity);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWeatherForecast(writer: SerializationWriter, serverWeatherForecast: Partial<ServerWeatherForecast> | undefined | null = {}) : void {
    if (serverWeatherForecast) {
        writer.writeDateOnlyValue("date", serverWeatherForecast.date);
        writer.writeStringValue("summary", serverWeatherForecast.summary);
        writer.writeNumberValue("temperatureC", serverWeatherForecast.temperatureC);
        writer.writeNumberValue("temperatureF", serverWeatherForecast.temperatureF);
    }
}
export interface ServerCustomersEndPointsCustomersCreateCreateCustomersRequest extends Parsable {
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The price property
     */
    price?: number | null;
    /**
     * The stockQuantity property
     */
    stockQuantity?: number | null;
}
export interface ServerCustomersEndPointsCustomersCreateCreateCustomersResponse extends Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The price property
     */
    price?: number | null;
    /**
     * The stockQuantity property
     */
    stockQuantity?: number | null;
}
export interface ServerProductsEndPointsCreateProductCreateProductRequest extends Parsable {
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The price property
     */
    price?: number | null;
    /**
     * The stockQuantity property
     */
    stockQuantity?: number | null;
}
export interface ServerProductsEndPointsCreateProductCreateProductResponse extends Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The price property
     */
    price?: number | null;
    /**
     * The stockQuantity property
     */
    stockQuantity?: number | null;
}
export interface ServerProductsEndPointsGetProductsGetProductsResponse extends Parsable {
    /**
     * The products property
     */
    products?: ServerProductsEndPointsGetProductsProductItem[] | null;
}
export interface ServerProductsEndPointsGetProductsProductItem extends Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The isActive property
     */
    isActive?: boolean | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The price property
     */
    price?: number | null;
    /**
     * The stockQuantity property
     */
    stockQuantity?: number | null;
}
export interface ServerWeatherForecast extends Parsable {
    /**
     * The date property
     */
    date?: DateOnly | null;
    /**
     * The summary property
     */
    summary?: string | null;
    /**
     * The temperatureC property
     */
    temperatureC?: number | null;
    /**
     * The temperatureF property
     */
    temperatureF?: number | null;
}
/* tslint:enable */
/* eslint-enable */
